title: Jack Potter # your name (or website title) here
logo: "/images/computerpic2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Freelance programmer, software developer and hacker of all things from the UK. 
  <br><br>
  If you would like to reach me, you can email me at jackjpotter@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
